language: go
sudo: required

# https://docs.travis-ci.com/user/languages/go/#go-import-path
go_import_path: github.com/etix/mirrorbits

go:
  - "1.10.x"
  - "1.11.x"
  - master

os:
  - linux

matrix:
  allow_failures:
    - go: master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PROTOCBIN="$HOME/protoc/bin"
  - export PATH="$PATH:$PROTOCBIN:$GOBIN"
  - go env

script:
  - make && make test
